### ISSUE TITLE
Please create a tag for Coq 8.20 in Coq Platform 2025.01

### ISSUE THREAD

**Issue by MSoegtropIMC** [mit-plv/rewriter#166]
The Coq team released Coq `8.20.0` on September 3rd, 2024.
The corresponding Coq Platform release `2025.01` should be released before **Jan 31st, 2025**.
It can be delayed in case of difficulties until Feb 28th, 2025, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (0.0.11) **does not work** with Coq `8.20.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit edcec730f68469475fdc4b78495ae941a5b320ec on repository https://github.com/mit-plv/rewriter - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.20, **preferably before Dec 31st, 2024**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before Dec 8th, 2024, it will be included in an early Coq Platform beta release of the for Coq 8.20.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.20~2025.01`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.20~2025.01.sh) which already supports Coq version `8.20.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/449

**Comment by JasonGross** [comment]
I've created https://github.com/mit-plv/rewriter/tree/v0.0.12, and will aim to add it to opam shortly

**Comment by JasonGross** [comment]
https://github.com/coq/opam/pull/3238

**Comment by MSoegtropIMC** [comment]
Perfect, many thanks for the quick work! I will update Coq Platform as soon as the opam package is merged and then close this issue. I will inform you asap if then also fiat-crypto compiles fine on all platforms.

**Comment by MSoegtropIMC** [comment]
Updated in Coq Platform to 0.0.12 via https://github.com/coq/platform/pull/452 => closing.
