### ISSUE TITLE
Opam package does not build on Mac when zsh is default shell

### ISSUE THREAD

**Issue by MSoegtropIMC** [mit-plv/rewriter#90]
@JasonGross : I have an issue with the Coq Platform release for Coq 8.16.1: the coq-rewrite opam package does not build if the default shell is zsh rather than bash (zsh is the default since a few years on macOS). This is because zsh does not have a realpath command (it has other ways to achieve the same, but not compatible). The issue is here:

https://github.com/mit-plv/rewriter/blob/de56173b42be33ea3bcf4f96a491bd5c2b30892e/src/Rewriter/Rewriter/Examples/PerfTesting/Makefile.variables#L4

**Comment by JasonGross** [comment]
Can you test #91?  (Let me know if you need me to tag a new release)

**Comment by MSoegtropIMC** [comment]
@JasonGross : thanks this works. I take it as patch over 0.0.6 (which is the version in the beta and I don't want to change it without good reason).

I have another issue, though - see the Coq Platform Zulip chat.
